[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
dokka = "2.1.0"



[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
#// https://plugins.gradle.org/plugin/org.jetbrains.dokka/2.0.0
#// classpath 'org.jetbrains.dokka:dokka-gradle-plugin:2.0.0'   // kotlindoc plugin, include dokka-javadoc plugin
#// https://plugins.gradle.org/plugin/org.jetbrains.dokka-javadoc/2.0.0
#// classpath("org.jetbrains.dokka-javadoc:org.jetbrains.dokka-javadoc.gradle.plugin:2.0.0") // javadoc plugin
#// NOTE: Do not place your application dependencies here; they belong
#classpath("org.jetbrains.dokka-javadoc:org.jetbrains.dokka-javadoc.gradle.plugin:2.1.0")
#// classpath 'org.jetbrains.dokka:dokka-gradle-plugin:2.1.0'
#// in the individual module build.gradle files
#classpath("org.jetbrains.dokka:kotlin-as-java-plugin:2.1.0") // kotlindoc to show as java doc style


